// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGv4s8yCdhtdEna5cqcWebOmUtIthvDk',
    appId: '1:119774208138:web:6ea1fabb29278884e28d73',
    messagingSenderId: '119774208138',
    projectId: 'socialm-cc87d',
    authDomain: 'socialm-cc87d.firebaseapp.com',
    storageBucket: 'socialm-cc87d.appspot.com',
    measurementId: 'G-GRPVSBY5XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDBRPaw8NNMxV-9w7TRPp0ftxqH0dIHs',
    appId: '1:119774208138:android:52f68da0e2040699e28d73',
    messagingSenderId: '119774208138',
    projectId: 'socialm-cc87d',
    storageBucket: 'socialm-cc87d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaglweMHoBDh1XyWAEMDtKpy5hveMHBXQ',
    appId: '1:119774208138:ios:b65f0108b1310918e28d73',
    messagingSenderId: '119774208138',
    projectId: 'socialm-cc87d',
    storageBucket: 'socialm-cc87d.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaglweMHoBDh1XyWAEMDtKpy5hveMHBXQ',
    appId: '1:119774208138:ios:b65f0108b1310918e28d73',
    messagingSenderId: '119774208138',
    projectId: 'socialm-cc87d',
    storageBucket: 'socialm-cc87d.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaGv4s8yCdhtdEna5cqcWebOmUtIthvDk',
    appId: '1:119774208138:web:c9a48ca6c39fb5f2e28d73',
    messagingSenderId: '119774208138',
    projectId: 'socialm-cc87d',
    authDomain: 'socialm-cc87d.firebaseapp.com',
    storageBucket: 'socialm-cc87d.appspot.com',
    measurementId: 'G-XHYHRYQ2T9',
  );
}
